//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargaProduto
    {
        public int Id { get; set; }
        public Nullable<int> CargaId { get; set; }
        public int ProdutoGradeId { get; set; }
        public Nullable<double> Quantidade { get; set; }
        public Nullable<int> temp_old_id { get; set; }
        public Nullable<double> Retorno { get; set; }
        public string Tipo { get; set; }
    
        public virtual Carga Carga { get; set; }
        public virtual ProdutoGrade ProdutoGrade { get; set; }
    }
}
