//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carga()
        {
            this.CargaProduto = new HashSet<CargaProduto>();
            this.Pedido = new HashSet<Pedido>();
            this.Receber = new HashSet<Receber>();
            this.ReceberBaixa = new HashSet<ReceberBaixa>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PracaId { get; set; }
        public Nullable<int> RepresentanteId { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<System.DateTime> DataAbertura { get; set; }
        public Nullable<System.DateTime> DataExportacao { get; set; }
        public Nullable<System.DateTime> DataRetorno { get; set; }
        public Nullable<System.DateTime> DataConferencia { get; set; }
        public Nullable<System.DateTime> DataFinalizacao { get; set; }
        public string Status { get; set; }
        public Nullable<int> temp_old_id { get; set; }
    
        public virtual Praca Praca { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargaProduto> CargaProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receber> Receber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceberBaixa> ReceberBaixa { get; set; }
    }
}
