//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepresentanteDBEntities : DbContext
    {
        public RepresentanteDBEntities()
            : base("name=RepresentanteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RepCarga> RepCarga { get; set; }
        public virtual DbSet<RepCargaProduto> RepCargaProduto { get; set; }
        public virtual DbSet<RepCategoria> RepCategoria { get; set; }
        public virtual DbSet<RepFornecedor> RepFornecedor { get; set; }
        public virtual DbSet<RepPraca> RepPraca { get; set; }
        public virtual DbSet<RepProduto> RepProduto { get; set; }
        public virtual DbSet<RepProdutoGrade> RepProdutoGrade { get; set; }
        public virtual DbSet<RepUsuario> RepUsuario { get; set; }
        public virtual DbSet<RepRepresentante> RepRepresentante { get; set; }
        public virtual DbSet<RepCargaAnterior> RepCargaAnterior { get; set; }
        public virtual DbSet<RepCargaConferencia> RepCargaConferencia { get; set; }
        public virtual DbSet<RepCidade> RepCidade { get; set; }
        public virtual DbSet<RepEstado> RepEstado { get; set; }
        public virtual DbSet<RepPais> RepPais { get; set; }
        public virtual DbSet<RepPedidoItem> RepPedidoItem { get; set; }
        public virtual DbSet<RepVendedor> RepVendedor { get; set; }
        public virtual DbSet<RepVendedorBase> RepVendedorBase { get; set; }
        public virtual DbSet<RepReceber> RepReceber { get; set; }
        public virtual DbSet<RepReceberBaixa> RepReceberBaixa { get; set; }
        public virtual DbSet<RepSuplementoProduto> RepSuplementoProduto { get; set; }
        public virtual DbSet<RepSuplemento> RepSuplemento { get; set; }
        public virtual DbSet<RepPedido> RepPedido { get; set; }
    }
}
