//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedidoItem = new HashSet<PedidoItem>();
        }
    
        public int Id { get; set; }
        public int VendedorId { get; set; }
        public int CargaId { get; set; }
        public string CodigoPedido { get; set; }
        public Nullable<System.DateTime> DataLancamento { get; set; }
        public Nullable<System.DateTime> DataPrevisaoRetorno { get; set; }
        public Nullable<System.DateTime> DataRetorno { get; set; }
        public Nullable<double> ValorCompra { get; set; }
        public Nullable<double> ValorComissao { get; set; }
        public Nullable<double> ValorLiquido { get; set; }
        public Nullable<double> ValorAcerto { get; set; }
        public string Status { get; set; }
        public Nullable<int> temp_old_id { get; set; }
        public Nullable<double> RecebidoAnterior { get; set; }
        public Nullable<int> QuantidadeRetorno { get; set; }
        public Nullable<int> Remarcado { get; set; }
        public Nullable<double> ValorPedido { get; set; }
        public Nullable<double> PercentualCompra { get; set; }
        public Nullable<double> FaixaComissao { get; set; }
        public Nullable<double> PercentualFaixa { get; set; }
    
        public virtual Carga Carga { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}
