//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoGrade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdutoGrade()
        {
            this.CargaProduto = new HashSet<CargaProduto>();
            this.PedidoItem = new HashSet<PedidoItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProdutoId { get; set; }
        public string Tamanho { get; set; }
        public string Cor { get; set; }
        public Nullable<double> ValorSaida { get; set; }
        public Nullable<System.DateTime> DataInicial { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public Nullable<double> PesoLiquido { get; set; }
        public Nullable<double> PesoBruto { get; set; }
        public string CodigoBarras { get; set; }
        public string Digito { get; set; }
        public Nullable<double> ValorCusto { get; set; }
        public Nullable<double> Quantidade { get; set; }
        public string Status { get; set; }
        public Nullable<int> temp_old_id { get; set; }
        public Nullable<int> temp_old_proid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargaProduto> CargaProduto { get; set; }
        public virtual Produto Produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}
