//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutosCarga
    {
        public string CodigoBarras { get; set; }
        public string Descricao { get; set; }
        public string Cor { get; set; }
        public string Tamanho { get; set; }
        public Nullable<double> Quantidade { get; set; }
        public Nullable<double> QuantidadeRetorno { get; set; }
        public Nullable<double> ValorSaida { get; set; }
        public Nullable<double> ValorCusto { get; set; }
        public int ProdutoId { get; set; }
        public int CargaId { get; set; }
        public int ProdutoGradeId { get; set; }
        public Nullable<int> PracaId { get; set; }
        public Nullable<int> RepresentanteId { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Mes { get; set; }
        public int CargaProdutoId { get; set; }
    }
}
