//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceberBaixa
    {
        public int Id { get; set; }
        public Nullable<int> ReceberId { get; set; }
        public Nullable<int> CargaId { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public Nullable<System.DateTime> DataBaixa { get; set; }
        public Nullable<int> temp_old_id { get; set; }
    
        public virtual Carga Carga { get; set; }
        public virtual Receber Receber { get; set; }
    }
}
