//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receber()
        {
            this.ReceberBaixa = new HashSet<ReceberBaixa>();
        }
    
        public int Id { get; set; }
        public Nullable<int> VendedorId { get; set; }
        public Nullable<int> CargaId { get; set; }
        public Nullable<int> Documento { get; set; }
        public string Serie { get; set; }
        public Nullable<double> ValorNF { get; set; }
        public Nullable<double> ValorDuplicata { get; set; }
        public Nullable<double> ValorAReceber { get; set; }
        public Nullable<double> ValorJuros { get; set; }
        public Nullable<double> ValorDesconto { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<System.DateTime> DataLancamento { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public string Observacoes { get; set; }
        public string Status { get; set; }
        public Nullable<int> temp_old_id { get; set; }
    
        public virtual Carga Carga { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceberBaixa> ReceberBaixa { get; set; }
    }
}
