//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepCarga
    {
        public long Id { get; set; }
        public Nullable<long> PracaId { get; set; }
        public Nullable<long> RepresentanteId { get; set; }
        public Nullable<long> Ano { get; set; }
        public Nullable<long> Mes { get; set; }
        public Nullable<System.DateTime> DataAbertura { get; set; }
        public Nullable<System.DateTime> DataExportacao { get; set; }
        public Nullable<System.DateTime> DataRetorno { get; set; }
        public Nullable<System.DateTime> DataConferencia { get; set; }
        public Nullable<System.DateTime> DataFinalizacao { get; set; }
        public string Status { get; set; }
    }
}
