//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepEstado
    {
        public long Id { get; set; }
        public string Descricao { get; set; }
        public string Sigla { get; set; }
        public long PaisId { get; set; }
    }
}
