//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepProdutosConferencia
    {
        public string CodigoBarras { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> QuantidadeCarga { get; set; }
        public Nullable<decimal> QuantidadeInformada { get; set; }
        public Nullable<decimal> Diferenca { get; set; }
        public long ProdutoId { get; set; }
        public long CargaProdutoId { get; set; }
        public long ProdutoGradeId { get; set; }
        public long CargaId { get; set; }
    }
}
