//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepPedido
    {
        public long Id { get; set; }
        public long VendedorId { get; set; }
        public long CargaId { get; set; }
        public string CodigoPedido { get; set; }
        public Nullable<System.DateTime> DataLancamento { get; set; }
        public Nullable<System.DateTime> DataPrevisaoRetorno { get; set; }
        public Nullable<System.DateTime> DataRetorno { get; set; }
        public Nullable<decimal> ValorPedido { get; set; }
        public Nullable<decimal> ValorCompra { get; set; }
        public Nullable<decimal> PercentualCompra { get; set; }
        public Nullable<decimal> FaixaComissao { get; set; }
        public Nullable<decimal> PercentualFaixa { get; set; }
        public Nullable<decimal> ValorComissao { get; set; }
        public Nullable<decimal> ValorLiquido { get; set; }
        public Nullable<decimal> ValorAcerto { get; set; }
        public Nullable<long> QuantidadeRetorno { get; set; }
        public Nullable<long> Remarcado { get; set; }
        public string Status { get; set; }
        public Nullable<long> CargaAtual { get; set; }
        public Nullable<long> RepresentanteId { get; set; }
        public Nullable<decimal> ValorAReceber { get; set; }
    }
}
