//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepProdutosCarga
    {
        public string CodigoBarras { get; set; }
        public string Descricao { get; set; }
        public string Cor { get; set; }
        public string Tamanho { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> QuantidadeRetorno { get; set; }
        public Nullable<decimal> ValorSaida { get; set; }
        public Nullable<decimal> ValorCusto { get; set; }
        public long ProdutoId { get; set; }        
        public long CargaId { get; set; }
        public long ProdutoGradeId { get; set; }
        public Nullable<long> PracaId { get; set; }
        public Nullable<long> RepresentanteId { get; set; }
        public Nullable<long> Ano { get; set; }
        public Nullable<long> Mes { get; set; }
    }
}
