//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepProdutoGrade
    {
        public long Id { get; set; }
        public Nullable<long> ProdutoId { get; set; }
        public string Tamanho { get; set; }
        public string Cor { get; set; }
        public Nullable<decimal> ValorSaida { get; set; }
        public Nullable<System.DateTime> DataInicial { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public Nullable<decimal> PesoLiquido { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public string CodigoBarras { get; set; }
        public string Digito { get; set; }
        public Nullable<decimal> ValorCusto { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public string Status { get; set; }
    }
}
