//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepReceber
    {
        public long Id { get; set; }
        public Nullable<long> VendedorId { get; set; }
        public Nullable<long> CargaId { get; set; }
        public Nullable<long> Documento { get; set; }
        public string Serie { get; set; }
        public Nullable<decimal> ValorNF { get; set; }
        public Nullable<decimal> ValorDuplicata { get; set; }
        public Nullable<decimal> ValorAReceber { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<System.DateTime> DataLancamento { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public string Observacoes { get; set; }
        public string Status { get; set; }
        public Nullable<long> QuantidadeRemarcado { get; set; }
    }
}
