//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepRecebimento
    {
        public long Id { get; set; }
        public string Tipo { get; set; }
        public Nullable<long> CargaId { get; set; }
        public long VendedorId { get; set; }
        public Nullable<long> ReceberId { get; set; }
        public Nullable<long> PedidoId { get; set; }
        public string CodigoPedido { get; set; }
        public Nullable<decimal> ValorRecebido { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public string Observacao { get; set; }
        public string FormaPagamento { get; set; }
    }
}
