//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepSuplemento
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string Situacao { get; set; }
        public string Observacao { get; set; }
    }
}
