//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuplementoProduto
    {
        public int Id { get; set; }
        public Nullable<int> SuplementoId { get; set; }
        public Nullable<int> ProdutoGradeId { get; set; }
        public Nullable<double> Quantidade { get; set; }
        public Nullable<int> temp_old_id { get; set; }
    
        public virtual ProdutoGrade ProdutoGrade { get; set; }
        public virtual Suplemento Suplemento { get; set; }
    }
}
