//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Totalizadores
    {
        public int Id { get; set; }
        public Nullable<double> QtdProdutos { get; set; }
        public Nullable<double> TotalProdutos { get; set; }
    }
}
